version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  database:
    image: mongo
    ports:
      - "27017:27017"

